file_format: "1"
id: mountain_breeze
name: Mountain Breeze
type: shield
url: https://afternoonlabs.com/breeze/
requires:
  - nice_nano_v2
features:
  - keys
siblings:
  - mountain_breeze_left
  - mountain_breeze_right
